title: 'Business and finance'
author: 857dbc7f-813d-48ef-b99e-aa6f80b770aa
template: careers/job_category/show
updated_by: 857dbc7f-813d-48ef-b99e-aa6f80b770aa
updated_at: 1704672442
blueprint: job_category
duplicated_from: 'job_category::animal-care'
